/**
 * Asserts the build actually produced a service worker.
 *
 * `@serwist/next` only runs under webpack. Under Turbopack — which is what a
 * bare `next build` uses in Next 16 — it prints a warning and does nothing, and
 * the build still exits 0. The result is a deploy with no service worker: no
 * offline support, no precache, and no failure anywhere to notice it.
 *
 * The `--webpack` flag in the build script is therefore load-bearing. This
 * check is what makes removing it fail loudly instead of silently shipping a
 * broken PWA.
 */
import { access } from 'node:fs/promises';

const SW_PATH = 'public/sw.js';

try {
  await access(SW_PATH);
  console.log(`service worker ok (${SW_PATH})`);
} catch {
  console.error(
    `\nerror  ${SW_PATH} was not generated by the build.\n` +
      `       @serwist/next requires webpack; a bare 'next build' uses Turbopack\n` +
      `       and skips it silently. Check that the build script still passes --webpack.\n`
  );
  process.exit(1);
}
